# Generated by Django 3.0.5 on 2022-05-18 12:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryName',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('catefory_name', models.CharField(default='Web development', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('subject', models.CharField(max_length=255)),
                ('message', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_name', models.ImageField(upload_to='static/main/img')),
                ('topic', models.CharField(max_length=255)),
                ('main_image_name', models.ImageField(upload_to='media/')),
                ('about_topic', models.TextField()),
                ('under_topic', models.CharField(max_length=255)),
                ('lesson_image_name', models.ImageField(upload_to='media/')),
                ('lesson_text', models.TextField()),
                ('category_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.CategoryName')),
            ],
        ),
    ]
