# Generated by Django 3.0.5 on 2022-06-15 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_categorylego'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='link_to_youtube',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='categorycs',
            name='link_to_youtube',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='categorylego',
            name='link_to_youtube',
            field=models.CharField(max_length=255),
        ),
    ]
