# Generated by Django 3.0.5 on 2022-06-18 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20220615_2250'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeacherCourse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(max_length=255)),
                ('link_to_youtube', models.CharField(max_length=255, null=True)),
                ('about_topic', models.TextField()),
            ],
        ),
    ]
