# Generated by Django 3.0.5 on 2022-06-18 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_auto_20220618_2020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teachercourse',
            name='author',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='teachercourse',
            name='author_info',
            field=models.CharField(max_length=255),
        ),
    ]
